### ISSUE TITLE
Make the canvas responsive

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/d3-map#1]
Make the canvas responsive i.e. the size of the canvas should fit multiple screen sizes.

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #1

Steps for completing the task:

1.    Fork the repo
2.   Make your necessary changes.
3.   Submit a PR

Leave a star if you like the project!

**Comment by rongg** [comment]
Will do!

**Comment by priyanshbalyan** [comment]
@rongg Feel free to submit a PR!
