### ISSUE TITLE
Add media query related margin for mobile view

### ISSUE THREAD

**Issue by priyanshbalyan** [priyanshbalyan/d3-map#3]
If the app is viewed on a phone screen the globe visualisation and text start to overlap with each other. Add a media query CSS top margin to the canvas so the text doesn't overlap with the canvas when the app is viewed on a phone screen.

Claim this issue first by commenting here to prevent multiple people working on the same issue.

Raise a PR with a description that says Fixes #3

Step for completing the task:

1.  Fork the repo
2.  Make you necessary changes.
3.  Submit a PR

Leave a star if you like the project!

**Comment by brewswain** [comment]
Hey, I can work on this no problem! just for clarification as I don't have much experience with Vue/Nuxt, do you wish for a separate CSS file that handles media queries or do i slip this into the <script /> section of index.vue?

**Comment by priyanshbalyan** [comment]
Using the <style> section should work.

**Comment by brewswain** [comment]
Ok no prob will PR soon
